<?xml version="1.0"?>
<robot name="ship_lidars" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="ship_length" value="1.76" />
    <xacro:property name="ship_width" value="1.2" />
    <xacro:property name="ship_height" value="0.2" />

    <material name="grey">
        <color rgba="0.5 0.5 0.5 0.6"/>
    </material>

    <material name="blue">
        <color rgba="0.0 0.0 0.5 0.6"/>
    </material>
    
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${ship_length} ${ship_width} ${ship_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 ${ship_height/2.0}" rpy="0.0 0.0 0.0"/>
            <material name="blue"/>
        </visual>
    </link>

    <xacro:macro name="lidar_sensor_link" params="position">
        <link name="${position}_lidar_link">
            <visual>
                <geometry>
                    <box size="0.02 0.2 0.1"/>
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <material name="grey"/>
            </visual>
        </link>
    </xacro:macro>

    <xacro:lidar_sensor_link position="f"/>
    <xacro:lidar_sensor_link position="r"/>
    <xacro:lidar_sensor_link position="b"/>
    <xacro:lidar_sensor_link position="l"/>



    <joint name="base_f_lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="f_lidar_link"/>
        <origin xyz="${ship_length/2.0} 0.0 ${ship_height/2.0}" rpy="0.0 0.0 0.0"/>
    </joint>

    <joint name="base_r_lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="r_lidar_link"/>
        <origin xyz="0.22 ${-ship_width/2.0} ${ship_height/2.0}" rpy="0.0 0.0 -0.78"/>
    </joint>

    <joint name="base_b_lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="b_lidar_link"/>
        <origin xyz="${-ship_length/2.0} 0.0 ${ship_height/2.0}" rpy="0.0 0.0 3.14"/>
    </joint>

    <joint name="base_l_lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="l_lidar_link"/>
        <origin xyz="0.22 ${ship_width/2.0} ${ship_height/2.0}" rpy="0.0 0.0 0.78"/>
    </joint>

</robot>